### ISSUE TITLE
VSCode Will Not Load After Upgrading to 2.4

### ISSUE THREAD

**Issue by jimddavis** [arkane-systems/genie#289]
**Windows version (build number):**
21H2  22000.739

**Linux distribution:**
Ubuntu 20.04

**Kernel version:**
5.10.102.1-microsoft-standard-WSL2

**Genie version:**
2,3

**Describe the bug**
When I upgrade genie to version 2.4 VSCode will no longer load from within WSL and I get the following error when running VSCode from any directory (code . or code testfile.txt)

```
node:internal/modules/cjs/loader:990 throw err; ^

Error: Cannot find module '\\wsl.localhost\Ubuntu-20.04\mnt\c\Users\JimD\AppData\Local\Programs\Microsoft VS Code\Code.exe' at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15) at Module._load (node:internal/modules/cjs/loader:832:27) at Function.c._load (node:electron/js2c/asar_bundle:5:13343) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) at node:internal/main/run_main_module:17:47 { code: 'MODULE_NOT_FOUND', requireStack: []`
```

**Confirm that you are running inside the bottle:**
Yes

**To Reproduce**
I rolled back the WSL image to a backup confirmed VSCode ran fine.  Ran apt upgrade, and got the above error.  Started over and manually upgrding each package listed by apt list --upgradable regularly checking that VS Code worked and periodically restarting my computer.  Upgraded every package except genie and it all worked fine. Upgraded genie and VS Code runs fine UNTIL I restart WSL, then I get the above error.

**Expected behavior**
VSCode loads normally

I did look around the internet and posted on Stack overflow about this issue before posting this report.  I could not find any information about it, so I suspect it may be something odd with my configuration, but I do not know that what could be.  I have a basic Ubuntu setup for web development using Drupal.  Apache2, php8.1, MariaDB,https enabled, mailhog, apt-fast, things like that.  Nothing complicated at all.  I also have the Windows drivers installed to run Linux GUI apps.

The workaround for me is to just not upgrade genie to 2.4, but that means I have to manually upgrade all other packages instead of just running apt upgrade.

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x ] Yes.
